language: cpp
git:
  depth: 3
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
matrix:
  include:
  - os: linux
    compiler: gcc
    script:
    - cmake -DCMAKE_BUILD_TYPE=Release . -Bbuild
    - cmake --build build --config Release
    - cmake --build build --config Release --target test
  - os: windows
    language: cpp
    install:
    - choco install nsis 7zip
    script:
    - cmake . -Bbuild
    - cmake --build build
#    - cmake --build build --target test # this fails for what reason?
  - os: osx
    osx_image: xcode9.1
    script:
    - cmake -DCMAKE_BUILD_TYPE=Release . -Bbuild
    - cmake --build build --config Release
    - cmake --build build --config Release --target test
before_install:
- |
  if [[ $TRAVIS_OS_NAME == linux && "$CXX" = "g++" ]]; then
      export CXX="g++-8" CC="gcc-8"
  fi
- |
  if [[ $TRAVIS_OS_NAME == linux && "$CXX" = "clang++" ]]; then
      export CXX="clang++-3.7" CC="clang-3.7";
  fi
- cmake --version
script:
- echo script
after_failure:
- pwd
- ls
#branches:
#  only:
#  - /tag.*/
#  - /master/
